# server
server:
    port: 8081
# LOG
logging:
    config: classpath:logback.xml
# RedisCluster
myCluster:
    cluster:
        host: 192.168.3.118:9001,192.168.3.118:9002,192.168.3.118:9003,192.168.3.118:9004,192.168.3.118:9005,192.168.3.118:9006
        connectionTimeout: 3000
        soTimeout: 3000
        maxRedirections: 5
#freemarker
application:
    message: Hello, Boot
spring:
    redis:
      host: 192.168.3.3
      port: 6379
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
    #mysql jps
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.3.251:3306/jpatest
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: update
        show: true
    jackson:
        serialization:
            indent_output: true
    #此时restart类加载器还会初始化，但不会监视文件更新
    devtools:
        restart:
            enabled: false
management:
    info:
        git:
            mode: full